#!/usr/bin/env bash

set -efu

if [[ -x "${ORIGINAL_VBOX_MANAGE:-}" ]]; then
  if [[ -n "${VBOX_MANAGE_LOG:-}" ]]; then
    printf '%s\n' "$ORIGINAL_VBOX_MANAGE $*" >> "$VBOX_MANAGE_LOG"
  fi
  exec "$ORIGINAL_VBOX_MANAGE" "$@"
fi

exec false
