#!/bin/bash

DEFINE_string "boxname" "" "Vagrant box name"
DEFINE_string 'release' "precise" 'Ubuntu release'
DEFINE_string 'provider' "virtualbox" 'Vagrant provider'
DEFINE_string "output" "" "Where to bundle the vagrant box"
DEFINE_string "release_dir" "$BOXCAR/vagrant-$(TZ=UTC date +%Y%m%d-%H%M-$$)" "Vagrant instance workarea"
DEFINE_string "ssh_username" "ubuntu" "Vagrant ssh username"

DEFINE_string builddir "$BOXCAR/build" "Build directory"
DEFINE_string cachedir "$BOXCAR/build" "Cache directory"
