#!/bin/bash

#/ NAME
#/     seed-rvm.sh - copies rvm ruby binaries and runs build-docker.sh
#/
#/ SYNOPSIS
#/     seed-rvm.sh ssh_config rubies...

function remote_install {
  set -exfu; cd

  docker_install
}

function docker_install {
  local apt_install="sudo env DEBIAN_FRONTEND=noninteractive aptitude -y install"

  $apt_install software-properties-common
  sudo add-apt-repository -y ppa:dotcloud/lxc-docker
  sudo aptitude update
  $apt_install lxc-docker
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar

bootstrap="$BASH_SOURCE"

# entry point
function main {
  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
