#!/bin/bash

#/ NAME
#/     boxcar-debug - dumps info about the boxcar build
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu

  env | grep -i git
  ssh-agent
  ssh-add -list
  git clone https://github.com/destructuring/junas
  curl http://www.google.com > /dev/null
  false
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require br

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"; shift

  standard_hook "$bootstrap" "$pth_ssh_config" "$@"
}

require sub "$BASH_SOURCE" "$@"
