#!/bin/bash

#/ NAME
#/     boxcar-pinky - builds pinky-server
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu

  local apt_install="sudo env DEBIAN_FRONTEND=noninteractive aptitude -y install"

  sudo aptitude update
  $apt_install unzip libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl luarocks luajit lua5.1 libmemcached-dev libsasl2-dev libyaml-0-2 libyaml-dev libmysqlclient-dev

  sudo mkdir -p /data/pinky-server
  sudo chown ubuntu /data/pinky-server

  cd /data
  git clone git@github.com:ober/pinky-server

  cd /data/pinky-server
  make pinky-server
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require br

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"; shift

  standard_hook "$bootstrap" "$pth_ssh_config" "$@"
}

require sub "$BASH_SOURCE" "$@"
