#!/bin/bash

#/ NAME
#/     boxcar-true - empty boxcar script to test successful builds
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  true
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar

bootstrap="$BASH_SOURCE"

# entry point
function main {
  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
