#!/bin/bash

#/ NAME
#/     boxcar-update - updates apt packages
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu; cd

  export DEBIAN_FRONTEND="noninteractive"

  # update everything
  aptitude update
  if [[ "$(ps -o command 1 | tail -1)" != "/sbin/init" ]]; then
    mv /usr/bin/ischroot /usr/bin/ischroot.x
    ln -nfs $(which true) /usr/bin/ischroot
  fi
  aptitude -y dist-upgrade
  aptitude -y safe-upgrade
  if [[ "$(ps -o command 1 | tail -1)" != "/sbin/init" ]]; then
    mv /usr/bin/ischroot.x /usr/bin/ischroot
  fi

  # ssl updates
  update-ca-certificates --fresh > /dev/null

  # package cleanup
  aptitude clean

  # remove cached network configurations
  rm -rf /etc/udev/rules.d/70-persistent-net.rules /lib/udev/rules.d/75-persistent-net-generator.rules /dev/.udev /var/lib/dhcp3
  mkdir -p /etc/udev/rules.d/70-persistent-net.rules
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar
require boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  standard_root_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
