#!/usr/bin/env bash

#/ NAME
#/     boxcar-false - empty boxcar script to test failed builds
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -x

  env; echo

  id -a
  uname -a
  pwd
  false
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar
require boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  if [[ "$BUILD_IMAGE_PHASE" = "root" ]]; then
    "standard_${BUILD_IMAGE_PHASE}_hook" "$bootstrap" "$@"
  else
    standard_hook "$bootstrap" "$@"
  fi
}

require sub "$BASH_SOURCE" "$@"
