#!/bin/bash

#/ NAME
#/     boxcar-update - updates apt packages
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu; cd

  export DEBIAN_FRONTEND="noninteractive"

  # update everything
  aptitude update
  aptitude -y dist-upgrade
  aptitude -y safe-upgrade

  # ssl updates
  update-ca-certificates --fresh > /dev/null

  # package cleanup
  aptitude clean

  # remove cached network configurations
  rm -rfv /etc/udev/rules.d/70-persistent-net.rules
  mkdir -pv /etc/udev/rules.d/70-persistent-net.rules
  rm -fv /lib/udev/rules.d/75-persistent-net-generator.rules
  rm -rfv /dev/.udev/ /var/lib/dhcp3/*
}

if [[ "$#" = 0 ]]; then
  if [[ "$UID" = 0 ]]; then
    remote_install
    exit $?
  else
    rsync -ia "$0" "$0.root"
    sudo -E "$0.root"
    exit $?
  fi
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar
require boxcar_opt

bootstrap="$BASH_SOURCE"

# entry point
function main {
  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
