#!/bin/bash

#/ NAME
#/     boxcar-redis - builds redis
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu

  local ver_redis="2.6.9"
  local url_redis="http://redis.googlecode.com/files/redis-${ver_redis}.tar.gz"

  local tar_redis="$(mktemp -t XXXXXX)"
  wget -O "$tar_redis" "$url_redis"
  tar xfz "$tar_redis"
  cd "redis-${ver_redis}"
  rm -f "$tar_redis"
  make
  sudo make install PREFIX="/usr"
  cd
  rm -rf "redis-${ver_redis}"
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require br

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"; shift

  standard_hook "$bootstrap" "$pth_ssh_config" "$@"
}

require sub "$BASH_SOURCE" "$@"
