#!/bin/bash

#/ NAME
#/     seed-rvm.sh - copies rvm ruby binaries and runs install-rvm.sh
#/
#/ SYNOPSIS
#/     seed-rvm.sh ssh_config rubies...

function remote_install {
  set -exfu; cd

  local apt_install="sudo -E env DEBIAN_FRONTEND=noninteractive aptitude -y install"

  sudo -E aptitude update
  $apt_install htop libfuse-dev unzip

  git clone git@github.com:destructuring/home 
  mv home/.git .
  rm -rf home
  git reset --hard
  make
  pushd .junas
  make
  popd

  rm -f ~/boxcar-home ~/.git-env
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar

bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
