#!/bin/bash

#/ NAME
#/     seed-rvm.sh - copies rvm ruby binaries and runs install-rvm.sh
#/
#/ SYNOPSIS
#/     seed-rvm.sh ssh_config rubies...

function remote_rvm {
  local makecmd="$1"; shift

  set -exfu; cd

  local apt_install="sudo -E env DEBIAN_FRONTEND=noninteractive aptitude -y install"
  # minimum to build chef, chefspec, foodcritic, minitest-chef-handler, nokogiri, rvm
  sudo -E aptitude update
  $apt_install build-essential libxml2-dev libxslt-dev zlib1g-dev libssl-dev libreadline-dev libyaml-dev
  $apt_install gawk libsqlite3-dev sqlite3 autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev

  git clone git@github.com:destructuring/build-rvm
  cd build-rvm
}

function remote_build {
  remote_rvm
  mkdir -p vendor/cache/rvm
  rsync -ia ~/rvm/. vendor/cache/rvm/
  rm -rf ~/rvm
  make binary
  (set +f; mv *.bz2 ~/)
}

function remote_install {
  remote_rvm
  mkdir -p vendor/cache/rvm
  rsync -ia ~/rvm/. vendor/cache/rvm/
  rm -rf ~/rvm
  (set +f; mv ~/*.bz2 .)
  sudo env http_proxy=$http_proxy make install
  rm -rf ~/build-rvm
}

if [[ "$#" = 0 ]]; then
  case "${BUILD_IMAGE_PHASE:-}" in
    build)
      remote_build
      exit $?
      ;;
    install)
      remote_install
      exit $?
      ;;
    *)
      echo "ERROR: unknown build phase: $BUILD_IMAGE_PHASE" 1>&2
      exit 1
  esac
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar
require boxcar_opt
bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  case "${BUILD_IMAGE_PHASE:-}" in
    build)
      (set +f; rsync -ia -e "ssh -F '$pth_ssh_config'" $FLAGS_cachedir/rvm/. default:rvm/)
      custom_hook "$bootstrap" "$@"
      rsync -ia -e "ssh -F '$pth_ssh_config'" default:*.bz2 $FLAGS_cachedir/
      continue_image_hook "$@"
      ;;
    install)
      (set +f; rsync -ia -e "ssh -F '$pth_ssh_config'" $FLAGS_cachedir/rvm/. default:rvm/)
      (set +f; rsync -ia -e "ssh -F '$pth_ssh_config'" $FLAGS_cachedir/ree*bz2 $FLAGS_cachedir/ruby*bz2 default:)
      standard_hook "$bootstrap" "$@"
      ;;
    *)
      logger_fatal "unknown local build phase $BUILD_IMAGE_PHASE" 1>&2
      exit 1
  esac
}

require sub "$BASH_SOURCE" "$@"
