#!/bin/bash

#/ NAME
#/     boxcar-node - builds node/npm
#/
#/ SYNOPSIS
#/     called by train

function remote_install {
  set -exfu

  local ver_node="0.10.21"
  local url_node="http://nodejs.org/dist/v${ver_node}/node-v${ver_node}.tar.gz"

  local apt_install="sudo env DEBIAN_FRONTEND=noninteractive aptitude -y install"
  sudo aptitude update
  $apt_install libssl-dev

  local tar_node="$(mktemp -t XXXXXX)"
  wget -O "$tar_node" "$url_node"
  sudo mkdir -p /usr/local/src
  sudo tar xfz "$tar_node" -C "/usr/local/src"
  rm -f "$tar_node"
  cd "/usr/local/src/node-v${ver_node}"
  sudo ./configure --prefix="/usr/local"
  sudo make
  sudo make install
  cd /tmp
  sudo rm -rf "/usr/local/src"

  export NODE_PATH="/usr/local/lib/node_modules"
  local tmp_npm="$(mktemp -t XXXXXX)"
  curl -L http://npmjs.org/install.sh > "$tmp_npm"
  cat "$tmp_npm" | sudo env NODE_PATH=$NODE_PATH skipclean=no_tty_you_dumb_fucks sh
  rm -f "$tmp_npm"
  sudo npm install kexec -g
  sudo npm install jake -g
  sudo npm install coffee-script@1.2.0 -g
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar
require boxcar_opt
bootstrap="$BASH_SOURCE"

# entry point
function main {
  local pth_ssh_config="$1"

  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
