#!/bin/bash

#/ NAME
#/     seed-rvm.sh - copies rvm ruby binaries and runs build-docker.sh
#/
#/ SYNOPSIS
#/     seed-rvm.sh ssh_config rubies...

function remote_install {
  set -exfu

  sudo aptitude update
  sudo aptitude dist-upgrade -y
  sudo aptitude safe-upgrade -y
  sudo aptitude clean
}

if [[ "$#" = 0 ]]; then
  remote_install
  exit $?
fi

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require br
require br/image

bootstrap="$BASH_SOURCE"

# entry point
function main {
  standard_hook "$bootstrap" "$@"
}

require sub "$BASH_SOURCE" "$@"
