#!/bin/bash

#/ NAME
#/     seed-rvm.sh - copies rvm ruby binaries and runs install-rvm.sh
#/
#/ SYNOPSIS
#/     seed-rvm.sh ssh_config rubies...

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar

# entry point
function main {
  if [[ "$#" = 0 ]]; then
    logger_fatal "missing build layers"
    exit 1
  fi

  export OVERRIDE_boxname="${FLAGS_boxname}"
  export OVERRIDE_release_dir="${FLAGS_release_dir}"
  export OVERRIDE_output="${FLAGS_output}"
  export OVERRIDE_ssh_username="${FLAGS_ssh_username}"

  start_image_hook "$@"
}

require sub "$BASH_SOURCE" "$@"
