#!/bin/bash

#/ NAME
#/     build-all - builds vagrant boxes from scratch
#/
#/ SYNOPSIS
#/     bin/build all virtualbox precise
#/     bin/build all virtualbox precise precise clean ...
#/     bin/build all aws raring
#/     bin/build all aws raring raring clean ...

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"
require boxcar

DEFINE_boolean build "$FLAGS_FALSE" "Also run the :build hooks"

function run {
  logger_info "running $*"
  "$@"
}

function refresh {
  local nm_virt="$1"; shift
  local nm_input="$1"; shift
  local nm_output="$1"; shift

  local ssh_username="ubuntu"
  if [[ "$nm_virt" = "virtualbox" && "${1%%:*}" = "clean" ]]; then
    ssh_username="vagrant" # TODO this hack goes away if we make our own veewee builds
  fi

  if vagrant box list | awk -v box="$nm_output" -v virt="$nm_virt" '$1 == box && $2 == "(" virt ")" { counter += 1 } END { exit !counter }'; then
    vagrant box remove $nm_output $nm_virt
  fi

  (cd $FLAGS_builddir/${nm_output}.vagrant 2>&- && { vagrant destroy -f 2>&1 > /dev/null; } ) || true

  run $shome/bin/boxcar --provider $nm_virt --boxname $nm_input \
    --release_dir $FLAGS_builddir/${nm_output}.vagrant \
    --output $FLAGS_builddir/$nm_output.box \
    --ssh_username "$ssh_username" \
    "$@" 2>&1 | tee $FLAGS_builddir/$nm_output.log
  if [[ "$PIPESTATUS" != 0 ]]; then
    return "$PIPESTATUS"
  fi
  vagrant box add $nm_output $FLAGS_builddir/$nm_output.box

  rm -rf $FLAGS_builddir/${nm_output}.vagrant
}

function build_boxcars {
  local nm_virt="$1"; shift

  # setup the initial box import
  output="$1"; shift

  # build intermediate hooks
  for raw_hook in "$@"; do
    adjust_build_phase "$raw_hook"
    nm_hook="${raw_hook%%:*}"
    logger_info "hook: $nm_hook, phase: $BUILD_IMAGE_PHASE"
    input="$output"

    if [[ "$nm_hook" = "clean" ]]; then
      output="$output-${nm_hook}(pre)"
    elif [[ "$nm_hook" = "$nm_virt" ]]; then
      output="${output%-clean*}-clean"
    else
      output="$output-$(echo $raw_hook | perl -pe 's{:(\w+)}{($1)}g')"
    fi

    refresh $nm_virt $input $output $raw_hook
  done
}

function build_train {
  local env_distro="$FLAGS_release"
  local envsuffix=""
  
  if [[ "$FLAGS_provider" = "aws" ]]; then
    envsuffix="$(ryaml $shome/config/aws.yml environment)"
    if [[ -n "$envsuffix" ]]; then
      env_distro="${FLAGS_release}(${envsuffix})"
    fi
  fi

  mark_output
  mark_log "${env_distro}-${FLAGS_provider}"

  FLAGS_builddir="$BOXCAR/build/${env_distro}-${FLAGS_provider}"
  export OVERRIDE_builddir="$FLAGS_builddir"

  FLAGS_cachedir="$BOXCAR/build/${FLAGS_release}"
  export OVERRIDE_cachedir="$FLAGS_cachedir"

  local train="${env_distro}"

  if [[ "$#" = 0 ]]; then
    # take a vendor image, make a clean version with provider specifics
    build_boxcars ${FLAGS_provider}  $train             clean
    build_boxcars ${FLAGS_provider} "$train-clean(pre)" ${FLAGS_provider}
    train="$train-clean"

    if [[ "$FLAGS_build" = "$FLAGS_TRUE" ]]; then
      # build rvm ruby binaries
      build_boxcars ${FLAGS_provider} $train rvm:build
      train="$train-rvm(build)"
    else
      # install rvm binaries
      build_boxcars ${FLAGS_provider} $train rvm 
      train="$train-rvm"
    fi
  else
    build_boxcars "${FLAGS_provider}" "$@"
  fi
}

# entry point
function main {
  export OVERRIDE_provider="${FLAGS_provider}"
  build_train "$@"
}

require sub "$BASH_SOURCE" "$@"



