#!/bin/bash

#/ NAME
#/     vagrant new - create a new vagrant based on templates, then up, ssh
#/
#/ SYNOPSIS
#/     vagrant new NAME BOX PROVIDER

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local nm_vagrant="$1"; shift
  local nm_box="$1"; shift
  local nm_provider="$1"; shift

  if [[ ! -d $nm_vagrant ]]; then
    mkdir -p $nm_vagrant
    echo '*' > $nm_vagrant/.gitignore
  fi

  cd $nm_vagrant
  ln -nfs ../Vagrantfile .
  env box=$nm_box vagrant up --provider $nm_provider
  vagrant ssh -- "$@"
}

main "$@"
