#!/usr/bin/env bash

#/ NAME
#/     vagrant rsync - rsync with vagrant ssh-config
#/
#/ SYNOPSIS
#/     vagrant rsync ARGS_TO_RSYNC

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

DEFINE_string "host" "default" "Vagrant hostname"
DEFINE_boolean "agent" "$FLAGS_TRUE" "Use ssh agent"

# entry point
function main {
  local tmp_config="$(mktemp -d -t XXXXXX)"
  local d='$'

  if [[ "$FLAGS_agent" = "$FLAGS_TRUE" ]]; then
    vagrant ssh-config "$FLAGS_host" | grep -v IdentitiesOnly > $tmp_config/ssh_config
  else
    vagrant ssh-config "$FLAGS_host" > $tmp_config/ssh_config
  fi

  local cmd_ssh="$(which ssh)"

  cat > $tmp_config/ssh <<EOF
#!/usr/bin/env bash
exec $cmd_ssh -F $tmp_config/ssh_config "${d}@"
EOF
  chmod 755 $tmp_config/ssh

  PATH="$tmp_config:$PATH"
  rsync "$@"

  rm -rf $tmp_config
}

require sub "$BASH_SOURCE" "$@"
