#!/bin/bash

#/ NAME
#/     br -- br-admin wrapper for br gem
#/
#/ SYNOPSIS
#/     br

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  BUNDLE_GEMFILE="$shome/vendor/projects/boxcar/Gemfile" bundle exec vagrant "$@"
}

require sub "$BASH_SOURCE" "$@"
