#!/bin/bash

#/ NAME
#/     vagrant scp - scp with vagrant ssh-config
#/
#/ SYNOPSIS
#/     vagrant scp ARGS_TO_SCP

# figure out the project root under which bin, lib live
shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"

# load a jason bourne library
source "$shome/libexec/_jason"

# entry point
function main {
  local tmp_config="$(mktemp -d -t XXXXXX)"
  local d='$'

  $shome/libexec/vagrant ssh-config > $tmp_config/ssh_config

  local cmd_scp="$(which scp)"

  cat > $tmp_config/scp <<EOF
#!/bin/bash
exec $cmd_scp -F $tmp_config/ssh_config "${d}@"
EOF
  chmod 755 $tmp_config/scp

  PATH="$tmp_config:$PATH"
  scp "$@"

  rm -rf $tmp_config
}

main "$@"
