#!/usr/bin/env bash

set -efu

if [[ -f "$HOME/.boxcar/env" ]]; then
  source "$HOME/.boxcar/env"
fi

PATH="$HOME/.boxcar:$PATH"

if [[ -n "${GIT_USER:-}" ]]; then
  export GIT_SSH=$(mktemp -t XXXXXX)
  trap "rm -f $GIT_SSH" EXIT
  {
    printf "#!/bin/bash\n"
    printf "%s\n" 'shift; exec ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p ${GIT_PORT} ${GIT_USER}@localhost "$*"' 
  } > $GIT_SSH
  chmod 755 $GIT_SSH
fi

tries=0
while [[ "$tries" < 5 ]]; do
  if nc -z localhost "$GIT_PORT"; then
    break
  fi
  sleep 1
  tries="$((tries + 1))"
done
if [[ "$tries" == 5 ]]; then
  exit 1
fi

exec "$@"
